"use client";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-quartz.css";
import { AgGridReact } from "ag-grid-react";
import type { ColDef, GridApi } from "ag-grid-community";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, Download, ShieldCheck, Wifi, WifiOff, X } from "lucide-react";
import { gatewayFetch } from "../../lib/api/gateway-client";
import { streamGatewaySse } from "../../lib/realtime/sse-client";
import { releaseRiskEventSchema, releaseRiskListSchema, releaseRiskRecordSchema, type ChangedFile, type ReleaseRiskRecord, type RiskFactor } from "../../lib/schemas/release-risk";
import { useFrontendSession } from "../../providers/session-provider";
import { Badge } from "../ui/badge"; import { Button } from "../ui/button"; import { Card } from "../ui/card";

function parseChangedFiles(raw:string):ChangedFile[]{return raw.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).map(line=>{const [path,a="0",d="0",language="",change="modified"]=line.split("|").map(x=>x.trim());return {path,additions:Math.max(0,Number(a)||0),deletions:Math.max(0,Number(d)||0),language:language||undefined,change_type:(["added","modified","deleted","renamed"].includes(change)?change:"modified") as ChangedFile["change_type"]};});}
function riskClass(level?:string){return level==="CRITICAL"?"text-red-700":level==="HIGH"?"text-orange-700":level==="MEDIUM"?"text-amber-700":"text-emerald-700";}

function reconcileRiskFactorRows(api:GridApi<RiskFactor>,next:RiskFactor[]){
  const filterModel=api.getFilterModel(); const columnState=api.getColumnState(); const existing=new Map<string,RiskFactor>();
  api.forEachNode(node=>{if(node.data)existing.set(node.data.code,node.data)});
  const incoming=new Map(next.map(row=>[row.code,row])); const add:RiskFactor[]=[],update:RiskFactor[]=[],remove:RiskFactor[]=[];
  for(const row of next){if(existing.has(row.code))update.push(row);else add.push(row)}
  for(const [code,row] of existing){if(!incoming.has(code))remove.push(row)}
  api.applyTransaction({add,update,remove}); api.setFilterModel(filterModel); api.applyColumnState({state:columnState,applyOrder:true});
}

function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}

export function ReleaseRiskScreen(){const session=useFrontendSession(),qc=useQueryClient();const [selectedId,setSelectedId]=useState<string>("");const [lastLiveAt,setLastLiveAt]=useState(Date.now());const [tick,setTick]=useState(Date.now());const [drawer,setDrawer]=useState<RiskFactor|null>(null);const factorApi=useRef<GridApi<RiskFactor>|null>(null);const fileApi=useRef<GridApi<ChangedFile>|null>(null);
const list=useQuery({queryKey:["release-risk-list",session.tenantId],queryFn:()=>gatewayFetch("/api/v1/releases/risk-assessments?limit=50",session,{},releaseRiskListSchema),refetchInterval:30000});
useEffect(()=>{if(!selectedId&&list.data?.[0])setSelectedId(list.data[0].assessment_id)},[list.data,selectedId]);
const assessment=useQuery({queryKey:["release-risk",selectedId],enabled:Boolean(selectedId),queryFn:()=>gatewayFetch(`/api/v1/releases/risk-assessments/${selectedId}` as `/api/v1/${string}`,session,{},releaseRiskRecordSchema)});
const current=assessment.data??list.data?.find(x=>x.assessment_id===selectedId)??null;
useEffect(()=>{const timer=setInterval(()=>setTick(Date.now()),5000);return()=>clearInterval(timer)},[]);
useEffect(()=>{if(!selectedId)return;const ctrl=new AbortController();(async()=>{try{for await(const msg of streamGatewaySse(`/api/v1/releases/risk-assessments/${selectedId}/stream`,session,ctrl.signal)){setLastLiveAt(Date.now());if(msg.event==="heartbeat"||!msg.data)continue;const event=releaseRiskEventSchema.safeParse(JSON.parse(msg.data));if(!event.success)continue;if(event.data.event_type==="release.risk.completed"){const parsed=releaseRiskRecordSchema.safeParse(event.data.payload);if(parsed.success){qc.setQueryData(["release-risk",selectedId],parsed.data);qc.setQueryData<ReleaseRiskRecord[]>(["release-risk-list",session.tenantId],old=>old?.map(x=>x.assessment_id===selectedId?parsed.data:x)??[parsed.data]);const api=factorApi.current;if(api)reconcileRiskFactorRows(api,parsed.data.result?.factors??[])}}else if(event.data.event_type==="release.risk.started"){await qc.invalidateQueries({queryKey:["release-risk",selectedId]});}}}catch{}})();return()=>ctrl.abort()},[selectedId,session,qc]);
const stale=Boolean(current&&["ACCEPTED","QUEUED","RUNNING"].includes(current.status)&&tick-lastLiveAt>15000);
const mutation=useMutation({mutationFn:async(payload:Record<string,unknown>)=>gatewayFetch("/api/v1/releases/risk-assessments",session,{method:"POST",headers:{"content-type":"application/json","idempotency-key":crypto.randomUUID()},body:JSON.stringify(payload)},releaseRiskRecordSchema),onSuccess:r=>{qc.setQueryData<ReleaseRiskRecord[]>(["release-risk-list",session.tenantId],old=>[r,...(old??[]).filter(x=>x.assessment_id!==r.assessment_id)]);setSelectedId(r.assessment_id);setLastLiveAt(Date.now());}});
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),files=parseChangedFiles(String(d.get("files")??""));mutation.mutate({repository:String(d.get("repository")),release_id:String(d.get("release_id")),commit_sha:String(d.get("commit_sha")),target_environment:String(d.get("environment")||"production"),changed_file_details:files,policy:{changed_files:files.length,changed_services:Number(d.get("changed_services")||0),failed_workflows:Number(d.get("failed_workflows")||0),database_migration_changed:d.get("database_migration_changed")==="on",rollback_plan_verified:d.get("rollback_plan_verified")==="on",security_scan_critical_findings:Number(d.get("security_findings")||0),test_coverage_delta_percent:Number(d.get("coverage_delta")||0)}});}
const fileCols=useMemo<ColDef<ChangedFile>[]>(()=>[{field:"path",headerName:"Changed file",flex:2,minWidth:240,filter:true,sortable:true},{field:"change_type",headerName:"Change",filter:true,sortable:true},{field:"additions",headerName:"+",type:"numericColumn",sortable:true},{field:"deletions",headerName:"−",type:"numericColumn",sortable:true},{field:"language",headerName:"Language",filter:true,sortable:true}],[]);
const factorCols=useMemo<ColDef<RiskFactor>[]>(()=>[{field:"label",headerName:"Risk factor",flex:2,filter:true,sortable:true},{field:"points",headerName:"Points",type:"numericColumn",sort:"desc",sortable:true},{field:"observed_value",headerName:"Observed",filter:true},{field:"rationale",headerName:"Rationale",flex:3,filter:true}],[]);
const factors=current?.result?.factors??[], files=current?.changed_file_details??[];
function exportJson(){if(current)download(`${current.release_id}-risk.json`,JSON.stringify(current,null,2),"application/json")}
function exportCsv(){if(!current)return;const rows=[["factor","points","observed","rationale"],...factors.map(f=>[f.label,String(f.points),f.observed_value,f.rationale])];download(`${current.release_id}-risk.csv`,rows.map(r=>r.map(v=>`"${v.replaceAll('"','""')}"`).join(",")).join("\n"),"text/csv")}
return <div className="space-y-6"><header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-slate-500">Release assurance</p><h1 className="text-3xl font-semibold">Real-time Release Risk</h1><p className="mt-2 max-w-3xl text-sm text-slate-600">Assess release evidence, watch the authoritative score update live, preserve grid analysis state, and route high-risk releases into human review.</p></div><div className="flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={exportCsv} disabled={!current}><Download className="mr-2 h-4 w-4"/>CSV</Button><Button type="button" variant="outline" onClick={exportJson} disabled={!current}><Download className="mr-2 h-4 w-4"/>JSON</Button></div></header>
<div className="grid grid-cols-1 gap-4 xl:grid-cols-[360px_1fr]"><Card className="p-5"><h2 className="font-semibold">Assess release</h2><form className="mt-4 space-y-3" onSubmit={submit}><label className="block text-sm">Repository<input className="mt-1 w-full rounded-md border p-2" name="repository" required placeholder="org/service"/></label><label className="block text-sm">Release ID<input className="mt-1 w-full rounded-md border p-2" name="release_id" required/></label><label className="block text-sm">Commit SHA<input className="mt-1 w-full rounded-md border p-2" name="commit_sha" required pattern="[A-Fa-f0-9]{7,64}"/></label><label className="block text-sm">Environment<input className="mt-1 w-full rounded-md border p-2" name="environment" defaultValue="production"/></label><label className="block text-sm">Changed services<input className="mt-1 w-full rounded-md border p-2" name="changed_services" type="number" min="0" defaultValue="1"/></label><label className="block text-sm">Changed files <span className="text-slate-500">path|+|−|language|type</span><textarea className="mt-1 min-h-28 w-full rounded-md border p-2 font-mono text-xs" name="files" placeholder="src/api.ts|12|3|TypeScript|modified"/></label><div className="grid grid-cols-2 gap-2"><label className="text-sm">Failed workflows<input className="mt-1 w-full rounded-md border p-2" name="failed_workflows" type="number" min="0" defaultValue="0"/></label><label className="text-sm">Critical findings<input className="mt-1 w-full rounded-md border p-2" name="security_findings" type="number" min="0" defaultValue="0"/></label></div><label className="block text-sm">Coverage delta %<input className="mt-1 w-full rounded-md border p-2" name="coverage_delta" type="number" step="0.1" defaultValue="0"/></label><label className="flex gap-2 text-sm"><input name="database_migration_changed" type="checkbox"/> Database migration changed</label><label className="flex gap-2 text-sm"><input name="rollback_plan_verified" type="checkbox" defaultChecked/> Rollback plan verified</label><Button className="w-full" disabled={mutation.isPending}>{mutation.isPending?"Queueing…":"Calculate live risk"}</Button>{mutation.error&&<p role="alert" className="text-sm text-red-700">{mutation.error.message}</p>}</form></Card>
<div className="space-y-4"><Card className="p-5"><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><label className="text-sm font-medium">Release selector<select className="ml-2 rounded-md border p-2" value={selectedId} onChange={e=>{setSelectedId(e.target.value);setLastLiveAt(Date.now())}}><option value="">Select release</option>{list.data?.map(r=><option key={r.assessment_id} value={r.assessment_id}>{r.release_id} · {r.repository} · {r.status}</option>)}</select></label><div aria-live="polite" className="flex items-center gap-2 text-sm">{stale?<><WifiOff className="h-4 w-4 text-amber-700"/><Badge tone="warning">Stale live state</Badge></>:<><Wifi className="h-4 w-4 text-emerald-700"/><Badge tone="success">Live</Badge></>}<span className="text-slate-500">{current?.status??"No release selected"}</span></div></div></Card>
{current?<><div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Card className="p-4"><p className="text-xs uppercase text-slate-500">Risk score</p><p className={`text-4xl font-semibold ${riskClass(current.result?.level)}`}>{current.result?.score??"—"}<span className="text-base text-slate-400">/100</span></p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Decision</p><p className="mt-2 font-semibold">{current.result?.decision??"Calculating"}</p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Confidence</p><p className="mt-2 font-semibold">{current.result?`${Math.round(current.result.confidence*100)}%`:"—"}</p></Card><Card className="p-4"><p className="text-xs uppercase text-slate-500">Review gate</p>{current.result?.requires_human_review?<Link className="mt-2 inline-flex items-center font-semibold text-amber-700 underline" href="/approvals"><AlertTriangle className="mr-1 h-4 w-4"/>Required</Link>:<p className="mt-2 flex items-center font-semibold text-emerald-700"><ShieldCheck className="mr-1 h-4 w-4"/>Not required</p>}</Card></div>
<Card className="p-5"><h2 className="font-semibold">Changed files</h2><p className="mb-3 text-sm text-slate-500">Sort and filter are retained while live risk events update assessment data.</p><div className="ag-theme-quartz h-[320px] w-full"><AgGridReact<ChangedFile> rowData={files} columnDefs={fileCols} getRowId={p=>p.data.path} onGridReady={e=>{fileApi.current=e.api}} animateRows/></div></Card>
<Card className="p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Risk factors & score breakdown</h2><p className="text-sm text-slate-500">Select a row to inspect supporting rationale and evidence.</p></div><Badge>{current.result?.policy_version??"pending"}</Badge></div><div className="ag-theme-quartz mt-3 h-[340px] w-full"><AgGridReact<RiskFactor> rowData={factors} columnDefs={factorCols} getRowId={p=>p.data.code} onGridReady={e=>{factorApi.current=e.api}} onRowClicked={e=>setDrawer(e.data??null)} animateRows/></div></Card></>:<Card className="p-8 text-center text-slate-500">Select or submit a release to start the live risk workspace.</Card>}</div></div>
{drawer&&<div className="fixed inset-y-0 right-0 z-50 w-full max-w-lg border-l bg-white p-6 shadow-2xl" role="dialog" aria-modal="true" aria-label="Risk evidence"><div className="flex items-start justify-between"><div><p className="text-xs uppercase text-slate-500">Evidence drawer</p><h2 className="text-xl font-semibold">{drawer.label}</h2></div><Button type="button" variant="outline" onClick={()=>setDrawer(null)} aria-label="Close evidence drawer"><X className="h-4 w-4"/></Button></div><dl className="mt-6 space-y-4 text-sm"><div><dt className="font-semibold">Risk points</dt><dd>{drawer.points}</dd></div><div><dt className="font-semibold">Observed value</dt><dd>{drawer.observed_value}</dd></div><div><dt className="font-semibold">Rationale</dt><dd>{drawer.rationale}</dd></div><div><dt className="font-semibold">Evidence IDs</dt><dd>{current?.result?.evidence_ids.length?current.result.evidence_ids.join(", "):"No external evidence IDs attached to this deterministic policy factor."}</dd></div></dl></div>}</div>}
