"use client";
import { useEffect,useState } from "react";
import { useParams } from "next/navigation";
const gateway=process.env.NEXT_PUBLIC_GATEWAY_URL??"http://localhost:4000";
const tenantId="11111111-1111-4111-8111-111111111111";
type Locator={kind:"text"|"page"|"timecode"|"code";page_number?:number;start_ms?:number;end_ms?:number;path?:string;start_line?:number;end_line?:number;chunk_ordinal?:number};
type Preview={citation:{citation_id:string;title:string;source_key:string;source_version:string;evidence_sha256:string;locator:Locator;service?:string|null;environment?:string|null;team?:string|null;document_kind?:string|null};excerpt:string;accessible:boolean};
function locatorText(l:Locator){if(l.kind==="page")return `Page ${l.page_number}`;if(l.kind==="timecode")return `${((l.start_ms??0)/1000).toFixed(1)}s–${((l.end_ms??0)/1000).toFixed(1)}s`;if(l.kind==="code")return `${l.path}:${l.start_line}-${l.end_line}`;return l.chunk_ordinal===undefined?"Text evidence":`Chunk ${l.chunk_ordinal}`;}
export default function CitationPage(){
 const params=useParams<{citationId:string}>();const id=params.citationId;const [data,setData]=useState<Preview|null>(null);const [error,setError]=useState("");
 useEffect(()=>{const c=new AbortController();void(async()=>{try{const r=await fetch(`${gateway}/api/v1/citations/${encodeURIComponent(id)}`,{headers:{"x-tenant-id":tenantId,"x-correlation-id":crypto.randomUUID()},cache:"no-store",signal:c.signal});if(!r.ok)throw new Error(r.status===404?"Citation is not accessible under the current authorization scope.":`Citation request failed with ${r.status}`);setData(await r.json() as Preview);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:"Citation unavailable");}})();return()=>c.abort();},[id]);
 if(error)return <main className="page"><section className="hero"><p className="eyebrow">Permission-safe citation</p><h1>Citation unavailable</h1><p className="error">{error}</p></section></main>;
 if(!data)return <main className="page"><section className="hero"><p className="eyebrow">Permission-safe citation</p><h1>Loading evidence…</h1></section></main>;
 const c=data.citation;return <main className="page citationPage"><section className="hero"><p className="eyebrow">Stable evidence citation</p><h1>{c.title}</h1><p className="lede">Citation <code>{c.citation_id}</code> resolves through the gateway and current retrieval authorization. Raw object-store URLs are never exposed.</p></section><section className="card citationMeta"><dl><dt>Locator</dt><dd>{locatorText(c.locator)}</dd><dt>Source</dt><dd>{c.source_key}</dd><dt>Source version</dt><dd><code>{c.source_version}</code></dd><dt>Evidence hash</dt><dd><code>{c.evidence_sha256}</code></dd><dt>Service</dt><dd>{c.service??"—"}</dd><dt>Environment</dt><dd>{c.environment??"—"}</dd><dt>Team</dt><dd>{c.team??"—"}</dd><dt>Type</dt><dd>{c.document_kind??"—"}</dd></dl></section><section className="card citationExcerpt"><p className="eyebrow">Authorized source preview</p><pre>{data.excerpt}</pre></section></main>;
}
