import "server-only";
import { createHash, randomBytes } from "node:crypto";

export type OidcDiscovery={authorization_endpoint:string;token_endpoint:string;userinfo_endpoint?:string};
export type OidcUser={sub:string;tenantId:string;roles:string[];displayName:string};
export function createOidcTransaction(){const verifier=randomBytes(48).toString("base64url");return {verifier,challenge:createHash("sha256").update(verifier).digest("base64url"),state:randomBytes(24).toString("base64url"),nonce:randomBytes(24).toString("base64url")};}
export async function discovery():Promise<OidcDiscovery>{const issuer=(process.env.OIDC_ISSUER_URL??"").replace(/\/$/,"");if(!issuer.startsWith("https://")&&process.env.NODE_ENV==="production")throw new Error("production OIDC issuer must use HTTPS");const r=await fetch(`${issuer}/.well-known/openid-configuration`,{cache:"no-store",signal:AbortSignal.timeout(5000)});if(!r.ok)throw new Error("OIDC discovery failed");return r.json() as Promise<OidcDiscovery>;}
export function redirectUri(){return `${(process.env.WEB_BASE_URL??"http://localhost:3000").replace(/\/$/,"")}/api/auth/callback`;}
export async function exchangeAuthorizationCode(code:string,verifier:string):Promise<OidcUser>{const client=process.env.OIDC_CLIENT_ID;if(!client)throw new Error("OIDC_CLIENT_ID not configured");const d=await discovery();const body=new URLSearchParams({grant_type:"authorization_code",code,redirect_uri:redirectUri(),client_id:client,code_verifier:verifier});if(process.env.OIDC_CLIENT_SECRET)body.set("client_secret",process.env.OIDC_CLIENT_SECRET);const token=await fetch(d.token_endpoint,{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body,cache:"no-store",signal:AbortSignal.timeout(5000)});if(!token.ok)throw new Error("OIDC token exchange failed");const t=await token.json() as {access_token?:string};if(!t.access_token||!d.userinfo_endpoint)throw new Error("OIDC userinfo unavailable");const ui=await fetch(d.userinfo_endpoint,{headers:{authorization:`Bearer ${t.access_token}`},cache:"no-store",signal:AbortSignal.timeout(5000)});if(!ui.ok)throw new Error("OIDC userinfo failed");const claims=await ui.json() as Record<string,unknown>;if(typeof claims.sub!=="string"||typeof claims.tenant_id!=="string"||!Array.isArray(claims.roles))throw new Error("required OIDC claims missing");return {sub:claims.sub,tenantId:claims.tenant_id,roles:claims.roles.filter((v):v is string=>typeof v==="string"),displayName:typeof claims.name==="string"?claims.name:claims.sub};}
