"use client";
import Link from "next/link";
import { useMemo,useState } from "react";
import { Activity,ArrowRight,CheckCircle2,GitCompare,ShieldCheck,TrendingUp,XCircle } from "lucide-react";
import { Badge } from "../../../components/ui/badge";
import { Card,CardContent,CardHeader } from "../../../components/ui/card";
import type { EvaluationDashboard, } from "../../../lib/schemas/evaluations";

const dashboard:EvaluationDashboard={
 runs:[
  {runId:"eval-053",label:"Dense baseline",model:"gpt-standard",promptVersion:"v1",retriever:"dense",aggregate:.944,passedRate:.948,createdAt:"2026-08-19T05:15:00Z",metrics:{Retrieval:.931,RAG:.949,Agent:.956,Safety:.991,Multimodal:.941},categories:{retrieval:.930,rca:.945,"release-risk":.951,visual:.938,"document-qa":.947,hallucination:.992,citation:.946}},
  {runId:"eval-056",label:"Prompt v2",model:"gpt-standard",promptVersion:"v2",retriever:"dense",aggregate:.964,passedRate:.972,createdAt:"2026-08-19T05:35:00Z",metrics:{Retrieval:.938,RAG:.971,Agent:.978,Safety:.995,Multimodal:.950},categories:{retrieval:.937,rca:.969,"release-risk":.974,visual:.949,"document-qa":.972,hallucination:.995,citation:.970}},
  {runId:"eval-058",label:"Fused candidate",model:"gpt-reasoning",promptVersion:"v2",retriever:"fused",aggregate:.981,passedRate:.984,createdAt:"2026-08-19T05:55:00Z",metrics:{Retrieval:.989,RAG:.980,Agent:.989,Safety:.998,Multimodal:.972},categories:{retrieval:.989,rca:.986,"release-risk":.982,visual:.989,"document-qa":.978,hallucination:.998,citation:.984}}
 ],
 cases:Array.from({length:28},(_,i)=>({caseId:`VD-${String(i+1).padStart(4,"0")}`,category:["retrieval","rca","release-risk","visual","document-qa","hallucination","citation"][i%7],score:i===8?.78:i===17?.81:.94+((i%5)*.01),passed:![8,17].includes(i),traceId:[8,17].includes(i)?`trace-${1000+i}`:null,correlationId:`corr-${2000+i}`}))
};

function pct(v:number){return `${(v*100).toFixed(1)}%`;}
export default function EvaluationsPage(){
 const [baseId,setBaseId]=useState(dashboard.runs[0].runId),[candidateId,setCandidateId]=useState(dashboard.runs.at(-1)!.runId),[category,setCategory]=useState("all");
 const baseline=dashboard.runs.find(r=>r.runId===baseId)!,candidate=dashboard.runs.find(r=>r.runId===candidateId)!;
 const metricRows=useMemo(()=>Object.keys(candidate.metrics).map(name=>({name,base:baseline.metrics[name]??0,candidate:candidate.metrics[name]??0,delta:(candidate.metrics[name]??0)-(baseline.metrics[name]??0)})),[baseline,candidate]);
 const categoryRows=useMemo(()=>Object.keys(candidate.categories).map(name=>({name,base:baseline.categories[name]??0,candidate:candidate.categories[name]??0,delta:(candidate.categories[name]??0)-(baseline.categories[name]??0)})),[baseline,candidate]);
 const aggregateDelta=candidate.aggregate-baseline.aggregate; const blockers=[...metricRows.filter(m=>m.delta<-.02).map(m=>`${m.name} regressed ${(m.delta*100).toFixed(1)} pp`),...(aggregateDelta<-.01?[`Aggregate regressed ${(aggregateDelta*100).toFixed(1)} pp`]:[])]; const gatePassed=blockers.length===0&&candidate.aggregate>=.90;
 const cases=dashboard.cases.filter(c=>category==="all"||c.category===category);
 return <div className="evalPage space-y-6"><header><p className="eyebrow">LLMOps · Evaluation</p><h1 className="text-3xl font-semibold">Evaluation Dashboard & Experiment Comparison</h1><p className="mt-2 max-w-4xl text-sm text-muted-foreground">Compare model, prompt and retriever experiments, inspect regressions, drill into dataset/category/case failures, follow trace links and enforce release-quality gates.</p></header>
 <div className="evalControls"><label>Baseline<select value={baseId} onChange={e=>setBaseId(e.target.value)}>{dashboard.runs.map(r=><option key={r.runId} value={r.runId}>{r.label} · {r.runId}</option>)}</select></label><GitCompare/><label>Candidate<select value={candidateId} onChange={e=>setCandidateId(e.target.value)}>{dashboard.runs.map(r=><option key={r.runId} value={r.runId}>{r.label} · {r.runId}</option>)}</select></label></div>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-5"><Metric label="Candidate quality" value={pct(candidate.aggregate)}/><Metric label="Pass rate" value={pct(candidate.passedRate)}/><Metric label="Aggregate delta" value={`${aggregateDelta>=0?"+":""}${(aggregateDelta*100).toFixed(2)} pp`}/><Metric label="Model" value={candidate.model}/><Metric label="Retriever" value={candidate.retriever}/></div>
 <Card><CardHeader><div className="flex items-center justify-between gap-4"><h2 className="flex items-center gap-2 font-semibold"><ShieldCheck className="h-4 w-4"/>Release gate</h2><Badge variant={gatePassed?"success":"danger"}>{gatePassed?"PASS":"BLOCK"}</Badge></div></CardHeader><CardContent>{gatePassed?<p className="text-sm text-emerald-300">Candidate satisfies aggregate and per-metric regression policy. It is eligible for promotion.</p>:<ul className="text-sm text-red-300">{blockers.map(b=><li key={b}>{b}</li>)}</ul>}</CardContent></Card>
 <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><CardHeader><h2 className="font-semibold">Metric regression comparison</h2></CardHeader><CardContent><div className="evalBars">{metricRows.map(m=><div key={m.name}><div className="evalBarLabel"><span>{m.name}</span><strong className={m.delta<0?"neg":"pos"}>{m.delta>=0?"+":""}{(m.delta*100).toFixed(2)} pp</strong></div><div className="evalTrack"><i style={{width:`${Math.max(2,m.base*100)}%`}}/><b style={{width:`${Math.max(2,m.candidate*100)}%`}}/></div><small>{pct(m.base)} → {pct(m.candidate)}</small></div>)}</div></CardContent></Card>
 <Card><CardHeader><h2 className="font-semibold">Category drill-down</h2></CardHeader><CardContent><div className="evalCategoryGrid">{categoryRows.map(r=><button key={r.name} onClick={()=>setCategory(r.name)}><span>{r.name}</span><strong>{pct(r.candidate)}</strong><small className={r.delta<0?"neg":"pos"}>{r.delta>=0?"+":""}{(r.delta*100).toFixed(2)} pp</small></button>)}</div></CardContent></Card></div>
 <Card><CardHeader><div className="flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><TrendingUp className="h-4 w-4"/>Historical quality trend</h2><span className="text-xs text-muted-foreground">Last {dashboard.runs.length} evaluation runs</span></div></CardHeader><CardContent><div className="trendChart" aria-label="Historical aggregate quality trend">{dashboard.runs.map((r,i)=><div key={r.runId} className="trendPoint"><div className="trendStem" style={{height:`${Math.max(10,(r.aggregate-.88)*650)}px`}}/><span>{pct(r.aggregate)}</span><small>{r.runId}<br/>{r.promptVersion} · {r.retriever}</small>{i<dashboard.runs.length-1&&<ArrowRight className="trendArrow"/>}</div>)}</div></CardContent></Card>
 <Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4"/>Case drill-down</h2><select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{Object.keys(candidate.categories).map(c=><option key={c}>{c}</option>)}</select></div></CardHeader><CardContent><div className="evalTable"><div className="evalRow evalHead"><span>Case</span><span>Category</span><span>Score</span><span>Status</span><span>Trace</span></div>{cases.map(c=><div className="evalRow" key={c.caseId}><span className="mono">{c.caseId}</span><span>{c.category}</span><span>{pct(c.score)}</span><span>{c.passed?<span className="ok"><CheckCircle2/>Pass</span>:<span className="bad"><XCircle/>Fail</span>}</span><span>{c.traceId?<Link href={`/agent-execution?trace_id=${encodeURIComponent(c.traceId)}`} className="traceLink">Open trace ↗</Link>:"—"}</span></div>)}</div></CardContent></Card>
 </div>;
}
function Metric({label,value}:{label:string,value:string}){return <Card><CardContent className="py-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold break-words">{value}</p></CardContent></Card>}
