"use client";
import { FormEvent, useEffect, useState } from "react";
type Job={job_id:string;status:string;detected_mime_type:string;sha256:string;size_bytes:number;error_message?:string|null};
const gateway=process.env.NEXT_PUBLIC_GATEWAY_URL??"http://localhost:4000";
const tenantId="11111111-1111-4111-8111-111111111111"; const userId="22222222-2222-4222-8222-222222222222";
export default function EvidencePage(){const [kind,setKind]=useState("documents");const [file,setFile]=useState<File|null>(null);const [job,setJob]=useState<Job|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();if(!file)return;setBusy(true);setError("");const form=new FormData();form.append("file",file);try{const r=await fetch(`${gateway}/api/v1/ingestion/${kind}`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID(),"x-tenant-id":tenantId,"x-user-id":userId,"x-correlation-id":crypto.randomUUID()},body:form});const b=await r.json();if(!r.ok)throw new Error(b?.message??"upload failed");setJob(b);}catch(x){setError(x instanceof Error?x.message:"upload failed");}finally{setBusy(false)}}
useEffect(()=>{if(!job||["READY","FAILED","QUARANTINED"].includes(job.status))return;const t=setInterval(async()=>{const r=await fetch(`${gateway}/api/v1/ingestion/jobs/${job.job_id}`,{headers:{"x-tenant-id":tenantId,"x-correlation-id":crypto.randomUUID()},cache:"no-store"});if(r.ok)setJob(await r.json());},1200);return()=>clearInterval(t)},[job]);
return <main className="page"><section className="hero"><p className="eyebrow">Multimodal Evidence</p><h1>Secure evidence intake</h1><p>One audited pipeline for documents, images, audio and video. Files are signature-validated, hashed, stored and queued before modality-specific processing.</p></section><section className="card"><form onSubmit={submit} className="form"><label>Evidence type<select value={kind} onChange={e=>setKind(e.target.value)}><option value="documents">Document</option><option value="images">Image</option><option value="audio">Audio</option><option value="video">Video</option></select></label><label>File<input type="file" required onChange={e=>setFile(e.target.files?.[0]??null)}/></label><button disabled={busy}>{busy?"Securing upload…":"Upload evidence"}</button></form>{error&&<p className="error">{error}</p>}{job&&<div className="result"><h2>Processing job</h2><dl><dt>Job</dt><dd>{job.job_id}</dd><dt>Status</dt><dd>{job.status}</dd><dt>Detected MIME</dt><dd>{job.detected_mime_type}</dd><dt>SHA-256</dt><dd className="mono">{job.sha256}</dd></dl></div>}</section></main>}
