"use client";
import { FormEvent, useEffect, useMemo, useRef, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Activity, AlertTriangle, Bot, Clock3, Coins, RefreshCw, Search, Wrench } from "lucide-react";
import { Badge } from "../../../components/ui/badge";
import { Button } from "../../../components/ui/button";
import { Card,CardContent,CardHeader } from "../../../components/ui/card";
import { gatewayFetch } from "../../../lib/api/gateway-client";
import { useFrontendSession } from "../../../components/providers/app-providers";
import { AgentExecutionProjectionSchema, type AgentExecutionProjection } from "../../../lib/schemas/agent-execution";
import { streamGatewaySse } from "../../../lib/realtime/sse-client";

type Connection="idle"|"connecting"|"live"|"replaying"|"disconnected";
const terminal=new Set(["COMPLETED","FAILED","CANCELLED","TIMED_OUT"]);
function ms(v:number|null){return v===null?"—":v<1000?`${v} ms`:`${(v/1000).toFixed(2)} s`;}
function tone(s:string){if(s==="completed"||s==="COMPLETED")return "success" as const;if(s==="failed"||s==="FAILED"||s==="timed_out"||s==="TIMED_OUT")return "danger" as const;if(s==="running"||s==="RUNNING")return "warning" as const;return "secondary" as const;}
export default function AgentExecutionPage(){
 const session=useFrontendSession(),qc=useQueryClient(); const [runId,setRunId]=useState(""); const [activeRun,setActiveRun]=useState(""); const [connection,setConnection]=useState<Connection>("idle"); const [error,setError]=useState(""); const abort=useRef<AbortController|null>(null);
 const query=useQuery({queryKey:["agent-execution",activeRun],enabled:Boolean(activeRun),queryFn:async()=>AgentExecutionProjectionSchema.parse(await gatewayFetch(`/api/v1/agent-execution/${activeRun}`,session))}); const view=query.data;
 async function refresh(){if(!activeRun)return;setConnection("replaying");const result=await qc.fetchQuery({queryKey:["agent-execution",activeRun],queryFn:async()=>AgentExecutionProjectionSchema.parse(await gatewayFetch(`/api/v1/agent-execution/${activeRun}`,session)),staleTime:0});setConnection(terminal.has(result.status)?"idle":"live");}
 async function connect(id:string){abort.current?.abort();const controller=new AbortController();abort.current=controller;setConnection("connecting");try{const base=AgentExecutionProjectionSchema.parse(await gatewayFetch(`/api/v1/agent-execution/${id}`,session));qc.setQueryData(["agent-execution",id],base);setConnection(terminal.has(base.status)?"idle":"live");if(terminal.has(base.status))return;const sse=streamGatewaySse(`/api/v1/agent-execution/${id}/stream`,session,controller.signal,String(base.last_sequence));for await(const message of sse){if(controller.signal.aborted)return;if(message.event==="events"){let events:unknown[]=[];try{const parsed=JSON.parse(message.data);events=Array.isArray(parsed)?parsed:[]}catch{events=[]}const current=qc.getQueryData<AgentExecutionProjection>(["agent-execution",id]);if(!current)continue;const seqs=events.map((e:any)=>Number(e.sequence_number)).filter(Number.isFinite);if(seqs.length&&Math.min(...seqs)!==current.last_sequence+1){await refresh();continue;}if(events.length){/* persisted-event delta arrived; authoritative projection is refreshed, never frontend-simulated */await refresh();}}}}catch(caught){if(controller.signal.aborted)return;setConnection("disconnected");setError(caught instanceof Error?caught.message:"Execution stream disconnected");}}
 function submit(e:FormEvent){e.preventDefault();setError("");const id=runId.trim();if(!id)return;setActiveRun(id);void connect(id);}
 useEffect(()=>()=>abort.current?.abort(),[]);
 const failures=useMemo(()=>view?.nodes.filter(n=>n.status==="failed"||n.status==="timed_out")??[],[view]);
 return <div className="space-y-6"><header><p className="eyebrow">Agent observability</p><h1 className="text-3xl font-semibold">Live Agent Execution</h1><p className="mt-2 max-w-4xl text-sm text-muted-foreground">Inspect persisted graph events, node status and duration, retries, sanitized tools, model roles, token/cost usage and failures. The UI never simulates execution state.</p></header>
 <Card><CardContent className="py-4"><form className="flex flex-col gap-3 md:flex-row" onSubmit={submit}><label className="sr-only" htmlFor="run-id">Graph run ID</label><input id="run-id" className="min-w-0 flex-1 rounded-lg border bg-background px-3 py-2" value={runId} onChange={e=>setRunId(e.target.value)} placeholder="Graph run UUID" required/><Button><Search className="mr-2 h-4 w-4"/>Inspect run</Button>{view&&<Button type="button" variant="outline" onClick={()=>void refresh()}><RefreshCw className="mr-2 h-4 w-4"/>Authoritative refresh</Button>}</form>{error&&<p className="mt-3 text-sm text-red-700" role="alert">{error}</p>}</CardContent></Card>
 {!view?<Card><CardContent className="py-12 text-center text-sm text-muted-foreground">Enter a persisted graph run ID. No execution state is synthesized before an authoritative response exists.</CardContent></Card>:<>
 <div className="grid grid-cols-2 gap-3 lg:grid-cols-6"><Metric label="Run" value={view.status}/><Metric label="Sequence" value={String(view.last_sequence)}/><Metric label="Nodes" value={String(view.nodes.length)}/><Metric label="Retries" value={String(view.nodes.reduce((a,n)=>a+n.retries,0))}/><Metric label="Tokens" value={(view.total_input_tokens+view.total_output_tokens).toLocaleString()}/><Metric label="Cost" value={`$${view.total_cost_usd.toFixed(4)}`}/></div>
 <Card><CardHeader><div className="flex items-center justify-between"><h2 className="font-semibold">Node graph</h2><Badge variant={connection==="live"?"success":"secondary"}>{connection}</Badge></div></CardHeader><CardContent>{view.nodes.length?<div className="grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">{view.nodes.map(n=><article key={n.node_id} className="rounded-xl border p-4"><div className="flex justify-between gap-3"><div><p className="font-medium">{n.label}</p><p className="text-xs text-muted-foreground">{n.node_id}</p></div><Badge variant={tone(n.status)}>{n.status}</Badge></div><dl className="mt-3 grid grid-cols-2 gap-2 text-xs"><dt>Duration</dt><dd>{ms(n.duration_ms)}</dd><dt>Retries</dt><dd>{n.retries}</dd><dt>Last event</dt><dd>#{n.last_sequence}</dd></dl>{n.error_message&&<p className="mt-3 rounded-lg bg-red-50 p-2 text-xs text-red-800">{n.error_code&&`${n.error_code}: `}{n.error_message}</p>}</article>)}</div>:<p className="text-sm text-muted-foreground">No persisted node events have been recorded for this run.</p>}</CardContent></Card>
 <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><CardHeader><h2 className="flex items-center gap-2 font-semibold"><Wrench className="h-4 w-4"/>Sanitized tool calls</h2></CardHeader><CardContent>{view.tools.length?<div className="space-y-3">{view.tools.map(t=><details key={t.call_id} className="rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">#{t.sequence_number} {t.tool_name} · {t.status}</summary><pre className="mt-2 overflow-auto text-xs">{JSON.stringify(t.arguments,null,2)}</pre>{t.result_summary&&<p className="mt-2 text-sm">{t.result_summary}</p>}</details>)}</div>:<p className="text-sm text-muted-foreground">No persisted tool-call telemetry.</p>}</CardContent></Card>
 <Card><CardHeader><h2 className="flex items-center gap-2 font-semibold"><Bot className="h-4 w-4"/>Model roles and usage</h2></CardHeader><CardContent>{view.models.length?<div className="space-y-3">{view.models.map(m=><article key={m.call_id} className="rounded-lg border p-3"><div className="flex justify-between"><span className="font-medium">{m.model_role}</span><Badge>{m.model_name??"model not recorded"}</Badge></div><p className="mt-2 text-xs text-muted-foreground">in {m.input_tokens.toLocaleString()} · out {m.output_tokens.toLocaleString()} · {ms(m.latency_ms)} · ${m.cost_usd.toFixed(6)}</p></article>)}</div>:<p className="text-sm text-muted-foreground">No persisted model-usage events.</p>}</CardContent></Card></div>
 <div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><CardHeader><h2 className="flex items-center gap-2 font-semibold"><AlertTriangle className="h-4 w-4"/>Failure drill-down</h2></CardHeader><CardContent>{failures.length?failures.map(n=><article key={n.node_id} className="mb-3 rounded-lg border border-red-200 bg-red-50 p-3"><p className="font-medium text-red-900">{n.label}</p><p className="text-sm text-red-800">{n.error_code??"NODE_FAILURE"}: {n.error_message??"Failure details were not persisted."}</p></article>):<p className="text-sm text-muted-foreground">No persisted node failures.</p>}</CardContent></Card>
 <Card><CardHeader><h2 className="flex items-center gap-2 font-semibold"><Activity className="h-4 w-4"/>Persisted event sequence</h2></CardHeader><CardContent><ol className="max-h-[28rem] space-y-2 overflow-auto">{view.events.map(e=><li key={e.event_id} className="rounded-lg border p-3 text-sm"><div className="flex justify-between gap-3"><span className="font-medium">#{e.sequence_number} {e.event_type}</span><span className="text-xs text-muted-foreground">{new Date(e.occurred_at).toLocaleTimeString()}</span></div><p className="text-xs text-muted-foreground">{e.node_name??"run"}</p></li>)}</ol></CardContent></Card></div>
 </>}</div>;
}
function Metric({label,value}:{label:string,value:string}){return <Card><CardContent className="py-4"><p className="text-xs uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold">{value}</p></CardContent></Card>}
