import { BadRequestException, Body, Controller, Get, Headers, HttpCode, MessageEvent, Param, Post, Query, Sse } from "@nestjs/common";
import { filter, map, merge, Observable, of } from "rxjs";
import type { CreateReleaseRiskRequest, ReleaseRiskEventEnvelope } from "./releases.dto";
import { ReleasesService } from "./releases.service";
function requiredHeader(value:string|undefined,name:string){if(!value?.trim())throw new BadRequestException(`${name} header is required`);return value.trim();}
function validateRequest(body:CreateReleaseRiskRequest){if(!body.repository?.trim()||!body.release_id?.trim()||!/^[A-Fa-f0-9]{7,64}$/.test(body.commit_sha??""))throw new BadRequestException("repository, release_id and a valid commit_sha are required");if(!Number.isInteger(body.policy?.changed_files)||body.policy.changed_files<0||!Number.isInteger(body.policy?.changed_services)||body.policy.changed_services<0)throw new BadRequestException("policy changed_files and changed_services must be non-negative integers");if(body.changed_file_details&&body.changed_file_details.length!==body.policy.changed_files)throw new BadRequestException("changed_file_details length must equal policy.changed_files");}
@Controller("releases") export class ReleasesController{constructor(private readonly service:ReleasesService){}
@Post("risk-assessments") @HttpCode(202) async create(@Body() body:CreateReleaseRiskRequest,@Headers("x-tenant-id") tenant?:string,@Headers("x-user-id") user?:string,@Headers("idempotency-key") key?:string,@Headers("x-correlation-id") corr?:string){validateRequest(body);return this.service.createRiskAssessment(body,requiredHeader(tenant,"x-tenant-id"),requiredHeader(user,"x-user-id"),requiredHeader(key,"idempotency-key"),corr??crypto.randomUUID());}
@Get("risk-assessments") async list(@Headers("x-tenant-id") tenant?:string,@Headers("x-correlation-id") corr?:string,@Query("limit") raw?:string){const limit=raw===undefined?50:Number(raw);if(!Number.isInteger(limit)||limit<1||limit>100)throw new BadRequestException("limit must be between 1 and 100");const r=await this.service.listRiskAssessments(requiredHeader(tenant,"x-tenant-id"),corr??crypto.randomUUID(),limit);if(r.statusCode>=400)throw new BadRequestException(r.body);return r.body;}
@Get("risk-assessments/:assessmentId") async get(@Param("assessmentId") id:string,@Headers("x-tenant-id") tenant?:string,@Headers("x-correlation-id") corr?:string){const r=await this.service.getRiskAssessment(id,requiredHeader(tenant,"x-tenant-id"),corr??crypto.randomUUID());if(r.statusCode>=400)throw new BadRequestException(r.body);return r.body;}
@Sse("risk-assessments/:assessmentId/stream") stream(@Param("assessmentId") id:string,@Headers("x-tenant-id") tenant?:string):Observable<MessageEvent>{const tenantId=requiredHeader(tenant,"x-tenant-id");const live$=this.service.events$.pipe(filter(e=>String(e.payload?.tenant_id??"")===tenantId&&String(e.payload?.assessment_id??"")===id),map(e=>({type:e.event_type,data:e} as MessageEvent)));return merge(live$,of({type:"heartbeat",data:{heartbeat:true}} as MessageEvent));}
}
