"use client";
import { useEffect,useState } from "react";
const gateway=process.env.NEXT_PUBLIC_GATEWAY_URL??"http://localhost:4000";
const tenantId="11111111-1111-4111-8111-111111111111";
type Approval={approval_id:string;action_type:string;risk:string;risk_score:number;status:string;version:number;expires_at:string;delegated_to?:string|null;evidence_summary:{title:string;summary:string;evidence_ids:string[];citation_ids:string[];risk_factors:string[]}};
export default function ApprovalsPage(){
 const [items,setItems]=useState<Approval[]>([]);const [error,setError]=useState("");const [busy,setBusy]=useState("");
 const load=async()=>{try{const r=await fetch(`${gateway}/api/v1/approvals`,{headers:{"x-tenant-id":tenantId,"x-correlation-id":crypto.randomUUID()},cache:"no-store"});if(!r.ok)throw new Error(`Approval queue failed with ${r.status}`);setItems(await r.json() as Approval[]);}catch(e){setError(e instanceof Error?e.message:"Approval queue unavailable");}};
 useEffect(()=>{void load();},[]);
 const decide=async(item:Approval,decision:"approve"|"reject"|"request_changes")=>{setBusy(item.approval_id);setError("");try{const comment=decision==="reject"?"Rejected after reviewer evidence check":decision==="request_changes"?"Additional evidence required":"Reviewed evidence and approved";const r=await fetch(`${gateway}/api/v1/approvals/${encodeURIComponent(item.approval_id)}/decision`,{method:"POST",headers:{"content-type":"application/json","x-tenant-id":tenantId,"x-correlation-id":crypto.randomUUID()},body:JSON.stringify({decision,comment,expected_version:item.version})});if(!r.ok)throw new Error(r.status===409?"This approval changed concurrently. Refresh the queue and review the latest state.":`Decision failed with ${r.status}`);await load();}catch(e){setError(e instanceof Error?e.message:"Decision failed");}finally{setBusy("");}};
 return <main className="page approvalPage"><section className="hero"><p className="eyebrow">Human-in-the-loop approval</p><h1>High-risk review queue</h1><p className="lede">Every production-risk decision is durable, versioned, signed, expiring, and concurrency-safe before workflow resume.</p>{error&&<p className="error">{error}</p>}</section><section className="approvalQueue">{items.length===0?<article className="card"><h2>No approvals waiting</h2><p>The queue is clear for the configured reviewer identity and roles.</p></article>:items.map(item=><article className="card approvalCard" key={item.approval_id}><div className="approvalHeader"><div><p className="eyebrow">{item.risk} · risk {item.risk_score}</p><h2>{item.evidence_summary.title}</h2></div><span>{item.status}</span></div><p>{item.evidence_summary.summary}</p><dl><dt>Action</dt><dd>{item.action_type}</dd><dt>Expires</dt><dd>{new Date(item.expires_at).toLocaleString()}</dd><dt>Version</dt><dd>{item.version}</dd><dt>Evidence</dt><dd>{item.evidence_summary.evidence_ids.join(", ")||"—"}</dd><dt>Citations</dt><dd>{item.evidence_summary.citation_ids.join(", ")||"—"}</dd></dl><div className="approvalActions"><button disabled={busy===item.approval_id} onClick={()=>void decide(item,"approve")}>Approve</button><button disabled={busy===item.approval_id} onClick={()=>void decide(item,"request_changes")}>Request changes</button><button disabled={busy===item.approval_id} onClick={()=>void decide(item,"reject")}>Reject</button></div></article>)}</section></main>;
}
