#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from verideploy.contracts.final_schemas import (
    ApiErrorResponse,
    CitationReference,
    EvidenceReference,
    KafkaEventEnvelope,
    RcaFinalResponse,
    ReleaseRiskFinalResponse,
    ReviewResponse,
    TimelineEntry,
    WebSocketEventEnvelope,
)

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "contracts/final"
PY_CLIENT = ROOT / "generated/clients/python/verideploy_contracts.py"
TS_CLIENT = ROOT / "generated/clients/typescript/contracts.ts"
MANIFEST = ROOT / "contracts/final/manifest.json"
BASELINE = ROOT / "contracts/compatibility/final-response-event-schemas-baseline.json"
MODELS = {
    "release-risk-response.v1": ReleaseRiskFinalResponse,
    "rca-response.v1": RcaFinalResponse,
    "evidence-reference.v1": EvidenceReference,
    "timeline-entry.v1": TimelineEntry,
    "review-response.v1": ReviewResponse,
    "api-error.v1": ApiErrorResponse,
    "websocket-envelope.v1": WebSocketEventEnvelope,
    "kafka-envelope.v1": KafkaEventEnvelope,
    "citation-reference.v1": CitationReference,
}


def canonical(value: Any) -> bytes:
    return json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode()


def digest(value: Any) -> str:
    return hashlib.sha256(canonical(value)).hexdigest()


def signature(schema: dict[str, Any]) -> dict[str, Any]:
    def node_sig(node: dict[str, Any]) -> dict[str, Any]:
        props = node.get("properties", {})
        out: dict[str, Any] = {
            "required": sorted(node.get("required", [])),
            "properties": {},
        }
        for key in ("type", "format", "$ref", "const"):
            if key in node:
                out[key] = node[key]
        if "enum" in node:
            out["enum"] = sorted(str(x) for x in node["enum"])
        for name, prop in sorted(props.items()):
            item: dict[str, Any] = {}
            for key in ("type", "format", "$ref", "const"):
                if key in prop:
                    item[key] = prop[key]
            if "enum" in prop:
                item["enum"] = sorted(str(x) for x in prop["enum"])
            if "anyOf" in prop:
                item["anyOf"] = sorted(
                    json.dumps({k: branch.get(k) for k in ("type", "format", "$ref", "const") if k in branch}, sort_keys=True)
                    for branch in prop["anyOf"]
                )
            out["properties"][name] = item
        return out

    return {
        "root": node_sig(schema),
        "defs": {name: node_sig(node) for name, node in sorted(schema.get("$defs", {}).items())},
    }


def compare_signature(old: dict[str, Any], new: dict[str, Any], label: str) -> list[str]:
    errors: list[str] = []
    for scope in ("root",):
        o = old.get(scope, {"required": [], "properties": {}})
        n = new.get(scope, {"required": [], "properties": {}})
        for key in ("type", "format", "$ref", "const"):
            if o.get(key) != n.get(key):
                errors.append(f"{label}: incompatible {key} change")
        if "enum" in o and not set(o["enum"]).issubset(set(n.get("enum", []))):
            errors.append(f"{label}: enum values removed")
        old_props, new_props = o["properties"], n["properties"]
        removed = sorted(set(old_props) - set(new_props))
        if removed:
            errors.append(f"{label}: removed properties: {removed}")
        newly_required = sorted(set(n["required"]) - set(o["required"]))
        if newly_required:
            errors.append(f"{label}: newly required properties: {newly_required}")
        for prop in sorted(set(old_props) & set(new_props)):
            before, after = old_props[prop], new_props[prop]
            for key in ("type", "format", "$ref", "const", "anyOf"):
                if before.get(key) != after.get(key):
                    errors.append(f"{label}.{prop}: incompatible {key} change")
            if "enum" in before and not set(before["enum"]).issubset(set(after.get("enum", []))):
                errors.append(f"{label}.{prop}: enum values removed")
    old_defs, new_defs = old.get("defs", {}), new.get("defs", {})
    for def_name in sorted(set(old_defs) - set(new_defs)):
        errors.append(f"{label}: removed definition {def_name}")
    for def_name in sorted(set(old_defs) & set(new_defs)):
        errors.extend(compare_signature({"root": old_defs[def_name]}, {"root": new_defs[def_name]}, f"{label}.$defs.{def_name}"))
    return errors


def python_client_text() -> str:
    return '''# Generated by scripts/generate_contracts.py. DO NOT EDIT.
from __future__ import annotations
from typing import Any, Literal, TypedDict

class CitationReference(TypedDict):
    citation_id: str
    evidence_id: str
    source_type: str
    locator: str
    claim_ids: list[str]

class EvidenceReference(TypedDict):
    evidence_id: str
    kind: str
    summary: str
    provenance_id: str
    citation_ids: list[str]
    observed_at: str | None
    confidence: float

class TimelineEntry(TypedDict):
    event_id: str
    occurred_at: str
    event_type: str
    summary: str
    evidence_ids: list[str]
    causal: bool

class ReviewResponse(TypedDict):
    review_id: str | None
    status: Literal["NOT_REQUIRED", "PENDING", "APPROVED", "REJECTED", "CHANGES_REQUESTED", "EXPIRED"]
    required: bool
    reviewer_id: str | None
    decision_reason: str | None
    decided_at: str | None
    signature_id: str | None

class RootCauseAssessment(TypedDict):
    root_cause: str
    confidence: float
    supporting_evidence_ids: list[str]
    alternative_causes: list[str]
    uncertainty: str | None

class ReleaseRiskFinalResponse(TypedDict):
    schema_version: Literal["1.0"]
    assessment_id: str
    tenant_id: str
    correlation_id: str
    release_id: str
    status: Literal["COMPLETED"]
    score: int
    risk_band: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    decision: Literal["PROCEED", "PROCEED_WITH_GUARDRAILS", "DELAY", "BLOCK"]
    confidence: float
    summary: str
    risk_factors: list[str]
    recommended_actions: list[str]
    evidence: list[EvidenceReference]
    citations: list[CitationReference]
    review: ReviewResponse
    completed_at: str

class RcaFinalResponse(TypedDict):
    schema_version: Literal["1.0"]
    investigation_id: str
    tenant_id: str
    correlation_id: str
    incident_id: str | None
    status: Literal["COMPLETED"]
    summary: str
    rca: RootCauseAssessment
    timeline: list[TimelineEntry]
    evidence: list[EvidenceReference]
    citations: list[CitationReference]
    review: ReviewResponse
    completed_at: str

class ApiErrorResponse(TypedDict):
    schema_version: Literal["1.0"]
    error_id: str
    code: str
    message: str
    correlation_id: str
    retryable: bool
    retry_after_seconds: int | None
    details: list[dict[str, Any]]

class FinalEventPayload(TypedDict):
    resource_type: Literal["release_risk", "incident_rca", "review", "timeline", "evidence"]
    resource_id: str
    status: str
    data: dict[str, Any]
    citation_ids: list[str]

class WebSocketEventEnvelope(TypedDict):
    schema_version: Literal["1.0"]
    event_id: str
    event_type: str
    tenant_id: str
    aggregate_id: str
    correlation_id: str
    sequence_number: int
    high_watermark: int
    occurred_at: str
    payload: FinalEventPayload

class KafkaEventEnvelope(TypedDict):
    schema_family: Literal["verideploy.final-event"]
    schema_version: Literal["1.0"]
    event_id: str
    event_type: str
    tenant_id: str
    aggregate_id: str
    ordering_key: str
    sequence_number: int
    correlation_id: str
    producer: str
    occurred_at: str
    causation_id: str | None
    trace_id: str | None
    retry_count: int
    payload: FinalEventPayload
'''


def ts_client_text() -> str:
    return '''// Generated by scripts/generate_contracts.py. DO NOT EDIT.
export type ReviewStatus = "NOT_REQUIRED" | "PENDING" | "APPROVED" | "REJECTED" | "CHANGES_REQUESTED" | "EXPIRED";
export type RiskBand = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
export type RiskDecision = "PROCEED" | "PROCEED_WITH_GUARDRAILS" | "DELAY" | "BLOCK";
export interface CitationReference { citation_id:string; evidence_id:string; source_type:"document"|"log"|"metric"|"trace"|"image"|"audio"|"video"|"code"|"release"; locator:string; claim_ids:string[]; }
export interface EvidenceReference { evidence_id:string; kind:string; summary:string; provenance_id:string; citation_ids:string[]; observed_at:string|null; confidence:number; }
export interface TimelineEntry { event_id:string; occurred_at:string; event_type:string; summary:string; evidence_ids:string[]; causal:boolean; }
export interface ReviewResponse { review_id:string|null; status:ReviewStatus; required:boolean; reviewer_id:string|null; decision_reason:string|null; decided_at:string|null; signature_id:string|null; }
export interface RootCauseAssessment { root_cause:string; confidence:number; supporting_evidence_ids:string[]; alternative_causes:string[]; uncertainty:string|null; }
export interface ReleaseRiskFinalResponse { schema_version:"1.0"; assessment_id:string; tenant_id:string; correlation_id:string; release_id:string; status:"COMPLETED"; score:number; risk_band:RiskBand; decision:RiskDecision; confidence:number; summary:string; risk_factors:string[]; recommended_actions:string[]; evidence:EvidenceReference[]; citations:CitationReference[]; review:ReviewResponse; completed_at:string; }
export interface RcaFinalResponse { schema_version:"1.0"; investigation_id:string; tenant_id:string; correlation_id:string; incident_id:string|null; status:"COMPLETED"; summary:string; rca:RootCauseAssessment; timeline:TimelineEntry[]; evidence:EvidenceReference[]; citations:CitationReference[]; review:ReviewResponse; completed_at:string; }
export interface ApiErrorResponse { schema_version:"1.0"; error_id:string; code:string; message:string; correlation_id:string; retryable:boolean; retry_after_seconds:number|null; details:Array<{field:string|null;code:string;message:string}>; }
export interface FinalEventPayload { resource_type:"release_risk"|"incident_rca"|"review"|"timeline"|"evidence"; resource_id:string; status:string; data:Record<string,unknown>; citation_ids:string[]; }
export interface WebSocketEventEnvelope { schema_version:"1.0"; event_id:string; event_type:string; tenant_id:string; aggregate_id:string; correlation_id:string; sequence_number:number; high_watermark:number; occurred_at:string; payload:FinalEventPayload; }
export interface KafkaEventEnvelope { schema_family:"verideploy.final-event"; schema_version:"1.0"; event_id:string; event_type:string; tenant_id:string; aggregate_id:string; ordering_key:string; sequence_number:number; correlation_id:string; producer:string; occurred_at:string; causation_id:string|null; trace_id:string|null; retry_count:number; payload:FinalEventPayload; }
'''

def generate(write_baseline: bool = False) -> dict[str, Any]:
    OUT.mkdir(parents=True, exist_ok=True)
    schemas: dict[str, dict[str, Any]] = {}
    entries: dict[str, Any] = {}
    for name, model in MODELS.items():
        schema = model.model_json_schema()
        schema["$id"] = f"https://schemas.verideploy.ai/final/{name}.json"
        path = OUT / f"{name}.schema.json"
        path.write_text(json.dumps(schema, indent=2, sort_keys=True) + "\n")
        schemas[name] = schema
        entries[name] = {"file": str(path.relative_to(ROOT)), "sha256": digest(schema), "signature": signature(schema)}
    manifest = {"schema_version": 1, "contract_version": "1.0", "schemas": entries}
    MANIFEST.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n")
    PY_CLIENT.parent.mkdir(parents=True, exist_ok=True); PY_CLIENT.write_text(python_client_text())
    TS_CLIENT.parent.mkdir(parents=True, exist_ok=True); TS_CLIENT.write_text(ts_client_text())
    if write_baseline or not BASELINE.exists():
        BASELINE.parent.mkdir(parents=True, exist_ok=True)
        BASELINE.write_text(json.dumps({"contract_version": "1.0", "schemas": {k:v["signature"] for k,v in entries.items()}}, indent=2, sort_keys=True) + "\n")
    return manifest


def validate_compatibility() -> list[str]:
    baseline = json.loads(BASELINE.read_text())
    errors: list[str] = []
    for name, old_sig in baseline["schemas"].items():
        model = MODELS.get(name)
        if model is None:
            errors.append(f"removed schema: {name}")
            continue
        errors.extend(compare_signature(old_sig, signature(model.model_json_schema()), name))
    return errors


if __name__ == "__main__":
    import sys
    write = "--write-baseline" in sys.argv
    generate(write_baseline=write)
    problems = validate_compatibility()
    print(json.dumps({"passed": not problems, "errors": problems}, sort_keys=True))
    raise SystemExit(0 if not problems else 1)
