{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.runtimeSecretName }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ required "externalSecrets.secretStoreRef is required" .Values.externalSecrets.secretStoreRef }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ .Values.global.runtimeSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ required "externalSecrets.remoteKey is required" .Values.externalSecrets.remoteKey }}
{{- end }}
