"use client";
import "ag-grid-community/styles/ag-grid.css";import "ag-grid-community/styles/ag-theme-quartz.css";
import { AgGridReact } from "ag-grid-react";import type { ColDef } from "ag-grid-community";import { useQuery } from "@tanstack/react-query";import { useMemo,useState } from "react";
import { gatewayFetch } from "../../lib/api/gateway-client";import type { FrontendSession } from "../../lib/auth/types";
type Row={audit_id:string;occurred_at:string;actor_type:string;actor_id:string;action:string;result:string;resource_type:string;resource_id:string;correlation_id:string;trace_id?:string|null;event_hash:string};
export function AuditViewer({session}:{session:FrontendSession}){const [search,setSearch]=useState("");const query=useQuery({queryKey:["audit",session.tenantId],queryFn:async()=>{const r=await gatewayFetch<{body?:{events?:Row[]};events?:Row[]}>("/api/v1/audit/events?limit=500",session);return (r as any).body?.events??(r as any).events??[] as Row[];},refetchInterval:30000});
const cols=useMemo<ColDef<Row>[]>(()=>[{field:"occurred_at",headerName:"Time",minWidth:190},{field:"actor_id",headerName:"Actor",minWidth:170},{field:"action",minWidth:190},{field:"result",minWidth:120},{field:"resource_type",headerName:"Resource",minWidth:140},{field:"resource_id",headerName:"Resource ID",minWidth:180},{field:"correlation_id",headerName:"Correlation",minWidth:180},{field:"trace_id",headerName:"Trace",minWidth:180},{field:"event_hash",headerName:"Event hash",minWidth:240}],[]);
const rows=(query.data??[]).filter(r=>!search||JSON.stringify(r).toLowerCase().includes(search.toLowerCase()));
return <div className="page"><section className="hero"><p className="eyebrow">Audit & compliance</p><h1>Reconstruct consequential actions</h1><p>Append-only, tenant-scoped audit events with correlation, trace and tamper-evidence hashes. Secret-bearing fields are redacted before persistence.</p></section><section className="card"><div className="toolbar"><input aria-label="Search audit events" placeholder="Search actor, action, resource, correlation…" value={search} onChange={e=>setSearch(e.target.value)}/><span>{rows.length} events</span></div>{query.isError?<p role="alert">Audit events could not be loaded.</p>:<div className="ag-theme-quartz" style={{height:620,width:"100%"}}><AgGridReact<Row> rowData={rows} columnDefs={cols} pagination paginationPageSize={50} animateRows={false}/></div>}</section></div>}
