"use client";
import { useQuery } from "@tanstack/react-query";
import { useParams } from "next/navigation";
import { gatewayFetch } from "../../../../lib/api/gateway-client";
import { CitationPreviewSchema } from "../../../../lib/schemas/citation";
import { useFrontendSession } from "../../../../providers/session-provider";
import { StatePanel } from "../../../../components/ui/state-panel";
function locatorText(l:{kind:string;page_number?:number;start_ms?:number;end_ms?:number;path?:string;start_line?:number;end_line?:number;chunk_ordinal?:number}){if(l.kind==="page")return `Page ${l.page_number}`;if(l.kind==="timecode")return `${((l.start_ms??0)/1000).toFixed(1)}s–${((l.end_ms??0)/1000).toFixed(1)}s`;if(l.kind==="code")return `${l.path}:${l.start_line}-${l.end_line}`;return l.chunk_ordinal===undefined?"Text evidence":`Chunk ${l.chunk_ordinal}`;}
export default function CitationPage(){const session=useFrontendSession();const params=useParams<{citationId:string}>();const id=params.citationId;const query=useQuery({queryKey:["citation",id,session.tenantId],queryFn:()=>gatewayFetch(`/api/v1/citations/${encodeURIComponent(id)}`,session,{},CitationPreviewSchema)});if(query.isLoading)return <div className="page"><StatePanel title="Loading citation" description="Resolving permission-safe evidence preview…"/></div>;if(query.error)return <div className="page"><StatePanel role="alert" title="Citation unavailable" description={query.error.message}/></div>;const data=query.data!,c=data.citation;return <div className="page citationPage"><section className="hero"><p className="eyebrow">Stable evidence citation</p><h1>{c.title}</h1><p className="lede">Citation <code>{c.citation_id}</code> resolves through the gateway and current retrieval authorization. Raw object-store URLs are never exposed.</p></section><section className="card citationMeta"><dl><dt>Locator</dt><dd>{locatorText(c.locator)}</dd><dt>Source</dt><dd>{c.source_key}</dd><dt>Source version</dt><dd><code>{c.source_version}</code></dd><dt>Evidence hash</dt><dd><code>{c.evidence_sha256}</code></dd><dt>Service</dt><dd>{c.service??"—"}</dd><dt>Environment</dt><dd>{c.environment??"—"}</dd><dt>Team</dt><dd>{c.team??"—"}</dd><dt>Type</dt><dd>{c.document_kind??"—"}</dd></dl></section><section className="card citationExcerpt"><p className="eyebrow">Authorized source preview</p><pre>{data.excerpt}</pre></section></div>}
